// SPDX-License-Identifier: AGPL-3.0-or-later
//! Bioinformatics and analytical chemistry algorithms.

pub mod chimera;
#[cfg(feature = "gpu")]
pub mod chimera_gpu;
pub mod dada2;
pub mod derep;
pub mod diversity;
#[cfg(feature = "gpu")]
pub mod diversity_gpu;
#[cfg(feature = "gpu")]
pub mod gemm_cached;
pub mod eic;
#[cfg(feature = "gpu")]
pub mod eic_gpu;
pub mod feature_table;
pub mod kmd;
pub mod kmer;
#[cfg(feature = "gpu")]
pub mod kriging;
pub mod merge_pairs;
pub mod pcoa;
#[cfg(feature = "gpu")]
pub mod pcoa_gpu;
pub mod quality;
#[cfg(feature = "gpu")]
pub mod quality_gpu;
#[cfg(feature = "gpu")]
pub mod rarefaction_gpu;
pub mod signal;
pub mod spectral_match;
#[cfg(feature = "gpu")]
pub mod spectral_match_gpu;
#[cfg(feature = "gpu")]
pub mod stats_gpu;
pub mod taxonomy;
#[cfg(feature = "gpu")]
pub mod streaming_gpu;
#[cfg(feature = "gpu")]
pub mod taxonomy_gpu;
pub mod tolerance_search;
pub mod unifrac;
