// SPDX-License-Identifier: AGPL-3.0-or-later
//! Bioinformatics and analytical chemistry algorithms.

pub mod chimera;
#[cfg(feature = "gpu")]
pub mod chimera_gpu;
pub mod dada2;
#[cfg(feature = "gpu")]
pub mod dada2_gpu;
pub mod decision_tree;
pub mod derep;
pub mod diversity;
#[cfg(feature = "gpu")]
pub mod diversity_gpu;
pub mod eic;
#[cfg(feature = "gpu")]
pub mod eic_gpu;
pub mod feature_table;
#[cfg(feature = "gpu")]
pub mod gemm_cached;
pub mod gillespie;
pub mod kmd;
pub mod kmer;
#[cfg(feature = "gpu")]
pub mod kriging;
pub mod merge_pairs;
pub mod ode;
pub mod pcoa;
#[cfg(feature = "gpu")]
pub mod pcoa_gpu;
pub mod phred;
pub mod qs_biofilm;
pub mod quality;
#[cfg(feature = "gpu")]
pub mod quality_gpu;
#[cfg(feature = "gpu")]
pub mod rarefaction_gpu;
pub mod robinson_foulds;
pub mod signal;
pub mod spectral_match;
#[cfg(feature = "gpu")]
pub mod spectral_match_gpu;
#[cfg(feature = "gpu")]
pub mod stats_gpu;
#[cfg(feature = "gpu")]
pub mod streaming_gpu;
pub mod taxonomy;
#[cfg(feature = "gpu")]
pub mod taxonomy_gpu;
pub mod tolerance_search;
pub mod unifrac;
