// SPDX-License-Identifier: AGPL-3.0-or-later
//! Bioinformatics and analytical chemistry algorithms.

pub mod adapter;
pub mod alignment;
pub mod ani;
#[cfg(feature = "gpu")]
pub mod ani_gpu;
#[cfg(feature = "gpu")]
pub mod batch_fitness_gpu;
pub mod bistable;
#[cfg(feature = "gpu")]
pub mod bistable_gpu;
pub mod bootstrap;
pub mod brain;
pub mod capacitor;
#[cfg(feature = "gpu")]
pub mod capacitor_gpu;
pub mod chimera;
#[cfg(feature = "gpu")]
pub mod chimera_gpu;
pub mod cooperation;
#[cfg(feature = "gpu")]
pub mod cooperation_gpu;
pub mod dada2;
#[cfg(feature = "gpu")]
pub mod dada2_gpu;
pub mod decision_tree;
pub mod derep;
#[cfg(feature = "gpu")]
pub mod derep_gpu;
pub mod diversity;
#[cfg(feature = "gpu")]
pub mod diversity_fusion_gpu;
#[cfg(feature = "gpu")]
pub mod diversity_gpu;
pub mod dnds;
#[cfg(feature = "gpu")]
pub mod dnds_gpu;
pub mod eic;
#[cfg(feature = "gpu")]
pub mod eic_gpu;
pub mod esn;
pub mod feature_table;
#[cfg(feature = "gpu")]
pub mod feature_table_gpu;
pub mod felsenstein;
#[cfg(feature = "gpu")]
pub mod fst_variance;
pub mod gbm;
#[cfg(feature = "gpu")]
pub mod gbm_gpu;
#[cfg(feature = "gpu")]
pub mod gemm_cached;
pub mod gillespie;
#[cfg(feature = "gpu")]
pub mod hamming_gpu;
pub mod hmm;
#[cfg(feature = "gpu")]
pub mod hmm_gpu;
#[cfg(feature = "gpu")]
pub mod jaccard_gpu;
pub mod kmd;
#[cfg(feature = "gpu")]
pub mod kmd_gpu;
#[cfg(feature = "gpu")]
pub mod kmd_grouping_gpu;
pub mod kmer;
#[cfg(feature = "gpu")]
pub mod kmer_gpu;
#[cfg(feature = "gpu")]
pub mod kriging;
#[cfg(feature = "gpu")]
pub mod locus_variance_gpu;
pub mod merge_pairs;
#[cfg(feature = "gpu")]
pub mod merge_pairs_gpu;
pub mod molecular_clock;
#[cfg(feature = "gpu")]
pub mod molecular_clock_gpu;
pub mod multi_signal;
#[cfg(feature = "gpu")]
pub mod multi_signal_gpu;
pub mod ncbi_data;
pub mod neighbor_joining;
#[cfg(feature = "gpu")]
pub mod neighbor_joining_gpu;
pub mod ode;
#[cfg(feature = "gpu")]
pub mod ode_sweep_gpu;
#[cfg(feature = "gpu")]
pub mod pairwise_l2_gpu;
pub mod pangenome;
#[cfg(feature = "gpu")]
pub mod pangenome_gpu;
pub mod pcoa;
#[cfg(feature = "gpu")]
pub mod pcoa_gpu;
pub mod phage_defense;
#[cfg(feature = "gpu")]
pub mod phage_defense_gpu;
pub mod phred;
pub mod placement;
pub mod qs_biofilm;
pub mod quality;
#[cfg(feature = "gpu")]
pub mod quality_gpu;
pub mod random_forest;
#[cfg(feature = "gpu")]
pub mod random_forest_gpu;
#[cfg(feature = "gpu")]
pub mod rarefaction_gpu;
pub mod reconciliation;
#[cfg(feature = "gpu")]
pub mod reconciliation_gpu;
pub mod robinson_foulds;
#[cfg(feature = "gpu")]
pub mod robinson_foulds_gpu;
pub mod signal;
#[cfg(feature = "gpu")]
pub mod signal_gpu;
pub mod snp;
#[cfg(feature = "gpu")]
pub mod snp_gpu;
#[cfg(feature = "gpu")]
pub mod spatial_payoff_gpu;
pub mod spectral_match;
#[cfg(feature = "gpu")]
pub mod spectral_match_gpu;
#[cfg(feature = "gpu")]
pub mod stats_extended_gpu;
#[cfg(feature = "gpu")]
pub mod stats_gpu;
#[cfg(feature = "gpu")]
pub mod streaming_gpu;
pub mod taxonomy;
#[cfg(feature = "gpu")]
pub mod taxonomy_gpu;
pub mod tolerance_search;
#[cfg(feature = "gpu")]
pub mod tolerance_search_gpu;
pub mod unifrac;
#[cfg(feature = "gpu")]
pub mod unifrac_gpu;
pub mod validation_helpers;
